banner/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [

]

basket/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [

]

comment/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
<<<<<<< HEAD
    path('', views.index , name="comments"),
=======
    path('', views.render, name="comments")
>>>>>>> product
]

product/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.urls import path
from . import views

urlpatterns = [
    path('create', views.create, name='product.create'),
    path('read', views.product_read, name='product.read'),
    path('delete/<int:id>', views.product_delete, name='product.delete'),


    ]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('banner.urls')),
    path('basket/', include('basket.urls')),
    #path('comment/', include('comment.urls')),
    path('product/', include('product.urls')),
    path('accounts/', include('user.urls')),
]

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.urls import path, include
from user import views

urlpatterns = [

    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name="register"),
    path('profile/', views.profile, name="profile"),
    path('dashboard', views.dashboard, name="register"),

    path('create_profile', views.create_profile, name="create_profile"),
    path('read_profile', views.read_profile, name="read_profile"),
    path('update_profile', views.update_profile, name="update_profile"),
    path('delete_profile', views.delete_profile, name="delete_profile"),
    path('admin', views.admin, name="delete_profile"),

]

banner/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Banner(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.DecimalField(max_digits=4, decimal_places=4)
    title = models.CharField(max_length=50, null=False)
    image = models.ImageField(upload_to='banner/static/images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

basket/models.py
from django.db import models

# Create your models here.

comment/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from product.models import Product


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=False)
    replys = models.ForeignKey("self" , on_delete=models.CASCADE)
    body = models.TextField()
    image = models.ImageField(upload_to='banner/static/images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

product/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=False)
    brand = models.CharField(max_length=50, null=False)
    seller = models.CharField(max_length=50, null=False)
    price = models.CharField(max_length=20, null=False)
    image = models.ImageField(upload_to='static/product/images/')
    colors = models.CharField(max_length=20, null=False)
    serial = models.CharField(max_length=10, null=False, unique=True)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ProductProperties(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField('product/static/images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

user/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/profile/images/')
    age = models.CharField(max_length=20, null=False)
    phone1 = models.CharField(max_length=20, null=False)
    phone2 = models.CharField(max_length=20, null=False)
    address = models.TextField()
    postcode = models.CharField(max_length=20, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

product/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'brand', 'seller', 'price', 'image', 'colors', 'serial', 'body']

user/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['fname', 'lname', 'image', 'biography', 'age', 'email', 'phone', 'address', 'postcode']

banner/views.py
from django.shortcuts import render

# Create your views here.

basket/views.py
from django.shortcuts import render

# Create your views here.

comment/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request , "main.html")

product/views.py
from django.shortcuts import render, redirect
from .forms import ProductForm
from .models import Product
# Create your views here.


def create(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    return render(request, 'product/create.html')


def product_read(request):
        products = Product.objects.all()
        return render(request, 'product/show_product.html', {'products': products})


def product_delete(request, id):
    products = Product.objects.get(id=id)
    products.delete()
    return redirect('product/show_product.html')

def update(request, id):

    if request.user.has_perm("course.change_course"):
        products = Product.objects.get(id=id)
        if request.method == "POST":
            form = ProductForm(request.POST, request.FILES, instance=products)
            if form.is_valid():
                form.save()
                return redirect('read.dashboard')
    else:
        return redirect('register')
    return render(request, 'products/update.html', {'products': products})

user/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


# Create your views here.

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def profile(request):
    return render(request, 'user/profile.html')


def dashboard(request):
    return render(request, 'admin/dashboard.html')



def create_profile():
    pass


def read_profile():
    pass


def update_profile():
    pass


def delete_profile():
    pass

def admin():
    pass

comment/templates/main.html
{% extends 'base.html' %}

{% block title %}comments{% endblock title %}

{% block content %}
<a href="#" class="btn btn-danger">ddddd</a>
{% endblock content %}

product/templates/create_product.html
{% block create %}

    <div class="container">
        <form class="form-group" action="{% url 'product.create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="id_title">Title: </label>
            <input class="form-control" id="id_title" name="title" type="text" placeholder="Title...">

            <label for="id_brand">Description: </label>
            <textarea class="form-control" id="id_brand" name="brand" type="text" placeholder="Description..."></textarea>

            <label for="id_price">Price: </label>
            <input class="form-control" id="id_price" name="price" type="text" placeholder="Price...">

            <label for="id_image">Image: </label>
            <input class="form-control" id="id_image" name="image" type="file">

            <label for="id_seller">seller: </label>
            <input class="form-control" id="id_seller" name="seller" type="text" placeholder="seller...">

            <input class="btn btn-success mt-2" type="submit" value="Create">
        </form>
    </div>


{% endblock %}

product/templates/product/create.html
{% extends 'base.html' %}

{% block dashboard %}

    <div class="container">
        <form class="form-group" action="{% url 'product.create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="id_title">Title: </label>
            <input class="form-control" id="id_title" name="title" type="text" placeholder="Title...">

            <label for="id_brand">Description: </label>
            <textarea class="form-control" id="id_brand" name="brand" type="text" placeholder="brand..."></textarea>

            <label for="id_price">Price: </label>
            <input class="form-control" id="id_price" name="price" type="text" placeholder="Price...">

            <label for="id_image">Image: </label>
            <input class="form-control" id="id_image" name="image" type="file">

            <label for="id_seller">seller: </label>
            <input class="form-control" id="id_seller" name="seller" type="text" placeholder="seller...">

            <label for="id_colors">colors: </label>
            <input class="form-control" id="id_colors" name="colors" type="text" placeholder="colors...">

            <label for="id_body">body: </label>
            <input class="form-control" id="id_body" name="body" type="text" placeholder="body...">

            <label for="id_serial">serial: </label>
            <input class="form-control" id="id_serial" name="serial" type="text" placeholder="serial...">

            <input class="btn btn-success mt-2" type="submit" value="Create">
        </form>
    </div>


{% endblock %}

product/templates/product/read.html
{% extends 'admin/dashboard.html' %}


{% block dashboard %}

          <h2>عنوان القسم</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>العنوان</th>
              <th>العنوان</th>
              <th>العنوان</th>
              <th>العنوان</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>أم.</td>
              <td>و.</td>
              <td>ثمّة.</td>
              <td>ويتّفق.</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>أضف.</td>
              <td>ما.</td>
              <td>من.</td>
              <td>أم.</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>دار.</td>
              <td>ذلك.</td>
              <td>يبق.</td>
              <td>المتحدة.</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>فكانت.</td>
              <td>الخارجية.</td>
              <td>الآخر.</td>
              <td>حتى.</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>أم.</td>
              <td>و.</td>
              <td>ثمّة.</td>
              <td>ويتّفق.</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>أضف.</td>
              <td>ما.</td>
              <td>من.</td>
              <td>أم.</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>دار.</td>
              <td>ذلك.</td>
              <td>يبق.</td>
              <td>المتحدة.</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>أم.</td>
              <td>و.</td>
              <td>ثمّة.</td>
              <td>ويتّفق.</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>أضف.</td>
              <td>ما.</td>
              <td>من.</td>
              <td>أم.</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>دار.</td>
              <td>ذلك.</td>
              <td>يبق.</td>
              <td>المتحدة.</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>أم.</td>
              <td>و.</td>
              <td>ثمّة.</td>
              <td>ويتّفق.</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>أضف.</td>
              <td>ما.</td>
              <td>من.</td>
              <td>أم.</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>دار.</td>
              <td>ذلك.</td>
              <td>يبق.</td>
              <td>المتحدة.</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>أم.</td>
              <td>و.</td>
              <td>ثمّة.</td>
              <td>ويتّفق.</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>أضف.</td>
              <td>ما.</td>
              <td>من.</td>
              <td>أم.</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>دار.</td>
              <td>ذلك.</td>
              <td>يبق.</td>
              <td>المتحدة.</td>
            </tr>
          </tbody>
        </table>
      </div>


{% endblock %}

product/templates/product/show.html
{% extends 'main.html' %}


{% block content %}


{% endblock %}

product/templates/product/show_product.html
{% block content %}

    <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for course in courses %}
            <div class="col-3">
              <div class="card shadow-sm align-items-center">
                <img src="/{{ product.image }}" width="250px" height="250px">
                <div class="card-body">
                  <p class="card-text">{{ product.body }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-success">View</button>
                      <button type="button" class="btn btn-sm btn-success">add to cart</button>
                       <a href="{% url 'product.delete' course.id %}" class="btn bg-danger">Delete</a>
                    </div>
                    <small class="text-muted">{{ product.seller }}</small>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}







      </div>
    </div>
  </div>

{% endblock %}

product/templates/product/update.html
{% extends 'admin/dashboard.html' %}


{% block dashboard %}


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
      
    {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.rtl.min.css' %}">
    
</head>
<body>
    {% block content %}
      
    {% endblock content %}
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.css' %}"></script>
</body>
</html>

user/templates/user/profile.html
<!doctype html>
<html lang="ar" dir="rtl">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>قالب لوحة القيادة · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard-rtl/">



    <!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap/css/bootstrap.rtl.min.css' %}" rel="stylesheet" integrity="sha384-4dNpRvNX0c/TdYEbYup8qbjvjaMrgUPh+g4I03CnNtANuv+VAvPL6LqdwzZKV38G" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/css/dashboard.rtl.css' %}" rel="stylesheet">
  </head>
  <body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">اسم الشركة</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="تبديل التنقل">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="بحث" aria-label="بحث">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">خروج</a>
    </li>
  </ul>
</header>

<div class="container-fluid">
  <div class="row">
    {% include 'user/sidebar.html' %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">لوحة القيادة</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">شارك</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">تصدير</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            هذا الاسبوع
          </button>
        </div>
      </div>


    {% block profile %}

    {% endblock %}
    </main>
  </div>
</div>


    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <script src="{% static 'bootstrap/js/feather.min.js' %}" integrity="sha384-EbSscX4STvYAC/DxHse8z5gEDaNiKAIGW+EpfzYTfQrgIlHywXXrM9SUIZ0BlyfF" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/Chart.min.js' %}" integrity="sha384-i+dHPTzZw7YVZOx9lbH5l6lP74sLRtMtwN2XjVqjf3uAGAREAF4LMIUDTWEVs4LI" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/dashboard.js' %}"></script>
  </body>
</html>

user/templates/user/sidebar.html
<h2>عنوان القسم</h2>
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home"></span>
              لوحة القيادة
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              أوامر
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              منتجات
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              الزبائن
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              التقارير
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              التكامل
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>التقارير المحفوظة</span>
          <a class="link-secondary" href="#" aria-label="أضف تقرير جديد">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              الشهر الحالي
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              الربع الأخير
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              ارتباط اجتماعي
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              بيع نهاية العام
            </a>
          </li>
        </ul>
      </div>
    </nav>